# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-ridgerun"
BBFILE_PATTERN_meta-ridgerun = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-ridgerun = "6"

LAYERDEPENDS_meta-ridgerun = "core"
LAYERSERIES_COMPAT_meta-ridgerun = "scarthgap"
